/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AFTONBLADET (https://sketchfab.com/wallander)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/darth-vader-by-makeamo-5b3371f4789c41eeaa691c9a3dfe1a96
Title: Darth Vader by Makeamo
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Darth(props) {
  const { nodes, materials } = useGLTF("/darth-transformed.glb");

  materials.Sabel_svart.emissiveIntensity = 20;
  materials.darthvader_VaderConsolesFlickermat.roughness = 0.2;
  materials.darthvader_VaderCapemat.roughness = 0.2;
  materials.darthvader_VaderCapemat.metalness = 0.7;
  materials.darthvader_VaderHelmetRimmat.roughness = 0.3;
  materials.darthvader_VaderHelmetRimmat.metalness = 0.6;
  materials.darthvader_VaderBodyArmourmat.roughness = 0.2;
  materials.darthvader_VaderBodyArmourmat.metalness = 0.9;

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DARTH_Sabel_vit_0.geometry}
        material={materials.Sabel_vit}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DARTH_darthvader_VaderConsolesFlickermat_0.geometry}
        material={materials.darthvader_VaderConsolesFlickermat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DARTH_darthvader_VaderCapemat_0.geometry}
        material={materials.darthvader_VaderCapemat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DARTH_darthvader_VaderHelmetRimmat_0.geometry}
        material={materials.darthvader_VaderHelmetRimmat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DARTH_darthvader_VaderBodyArmourmat_0.geometry}
        material={materials.darthvader_VaderBodyArmourmat}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DARTH_Laser_0.geometry}
        material={materials.Laser}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.DARTH_Sabel_svart_0.geometry}
        material={materials.Sabel_svart}
      />
    </group>
  );
}

useGLTF.preload("/darth-transformed.glb");
