/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 naboo_royal_starship.glb --transform --simplify
Author: hobbit84 (https://sketchfab.com/hobbit84)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/naboo-royal-starship-j-type-327-nubian-f631077977754b5591298ecfa201380b
Title: Naboo Royal Starship (J-type 327 Nubian)
*/

import React from "react";
import { Float, useGLTF } from "@react-three/drei";
import { AdditiveBlending, DoubleSide } from "three";
import { useJetEngineMaterial } from "./JetEngineMaterial";

export default function RoyalNaboo(props) {
  const { nodes, materials } = useGLTF("/naboo_royal_starship-transformed.glb");
  const { key, colorNode } = useJetEngineMaterial();

  materials["blinn1.002"].roughness = 0.15;
  materials["blinn1.002"].metalness = 1;
  materials["blinn1.002"].roughnessMap = null;

  return (
    <Float speed={2} floatIntensity={0.2} rotationIntensity={0.3}>
      <group {...props} dispose={null}>
        <group position={[-0.01, 0, 6.5]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_2.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_3.geometry}
            material={materials["aiwindow.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4.geometry}
            material={materials["blinn1.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials["blinn1.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials["blinn1.002"]}
          />
          <mesh position={[-1.48, -4.1, -0.36]}>
            <cylinderGeometry args={[0.2, 0.01, 2.9, 16, 8, true]} />
            <meshStandardNodeMaterial
              key={key}
              colorNode={colorNode}
              transparent
              blending={AdditiveBlending}
              side={DoubleSide}
              emissiveNode={colorNode}
            />
          </mesh>
          <mesh position={[1.48, -4.1, -0.36]}>
            <cylinderGeometry args={[0.2, 0.01, 2.9, 16, 8, true]} />
            <meshStandardNodeMaterial
              key={key}
              colorNode={colorNode}
              transparent
              blending={AdditiveBlending}
              side={DoubleSide}
              emissiveNode={colorNode}
            />
          </mesh>
          <mesh
            rotation={[Math.PI / 2, 0, 0]}
            position={[1.51, -2.68, -0.37]}
            renderOrder={-1}
          >
            <torusGeometry args={[0.2, 0.03, 24, 24]} />
            <meshStandardNodeMaterial
              color="red"
              transparent
              emissive="cyan"
              emissiveIntensity={10}
            />
          </mesh>
          <mesh
            rotation={[Math.PI / 2, 0, 0]}
            position={[-1.5, -2.68, -0.36]}
            renderOrder={-1}
          >
            <torusGeometry args={[0.2, 0.03, 24, 24]} />
            <meshStandardNodeMaterial
              color="cyan"
              transparent
              emissive="cyan"
              emissiveIntensity={10}
            />
          </mesh>
        </group>
      </group>
    </Float>
  );
}

useGLTF.preload("/naboo_royal_starship-transformed.glb");
